# Generated by Django 4.2.27 on 2026-02-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
